import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MenubarDemo } from '@/components/ui/manu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <MenubarDemo />
        </header>
        <main className="h-max py-10 items-center flex m-auto justify-center ">
          {children}
        </main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
